### ISSUE TITLE
Passing arguments to DroidMate's command line doesn't work.

### ISSUE THREAD

**Issue by jyotigajrani** [konrad-jamrozik/droidmate#4]
Hi,
I am able to run DroidMate with the inlined apks given in repository.
But for other apk(original and non-inlined) files, it is mentioned to run with -inline option.
I put one of apk in apks/inlined folder and run it using command as:

**./gradlew :projects:command:run -inline**

But this won't run the app and give build error as:
-------------------------------------------
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14-rc-2/userguide/gradle_daemon.html.
Starting daemon process: workingDir = /home/jyoti/cache/daemon/2.14-rc-2, daemonArgs: [/usr/lib/jvm/java-8-oracle/bin/java, -Xmx2048M, -Dfile.encoding=UTF-8, -Duser.country=IN, -Duser.language=en, -Duser.variant, -cp, /home/jyoti/cache/wrapper/dists/gradle-2.14-rc-2-all/6cjxff3vlyk77didltfk7gcfa/gradle-2.14-rc-2/lib/gradle-launcher-2.14-rc-2.jar, org.gradle.launcher.daemon.bootstrap.GradleDaemon, 2.14-rc-2]
Starting process 'Gradle build daemon'. Working directory: /home/jyoti/cache/daemon/2.14-rc-2 Command: /usr/lib/jvm/java-8-oracle/bin/java -Xmx2048M -Dfile.encoding=UTF-8 -Duser.country=IN -Duser.language=en -Duser.variant -cp /home/jyoti/cache/wrapper/dists/gradle-2.14-rc-2-all/6cjxff3vlyk77didltfk7gcfa/gradle-2.14-rc-2/lib/gradle-launcher-2.14-rc-2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 2.14-rc-2
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 0.996 secs.
Connected to daemon DaemonInfo{pid=7941, address=[47100ef7-a38a-4291-b6bb-3abfea089992 port:56262, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]], idle=false, lastBusy=1465373136464, context=DefaultDaemonContext[uid=95ea54a7-c562-4942-aee2-7d257c71c7f1,javaHome=/usr/lib/jvm/java-8-oracle,daemonRegistryDir=/home/jyoti/cache/daemon,pid=7941,idleTimeout=120000,daemonOpts=-Xmx2048M,-Dfile.encoding=UTF-8,-Duser.country=IN,-Duser.language=en,-Duser.variant]}. Dispatching request BuildAndStop{id=638fa168-dd84-4c1d-afaf-5a5f944a98af.1, currentDir=/home/jyoti/repo/dev/droidmate}.
Received result org.gradle.launcher.daemon.protocol.BuildStarted@3406472c from daemon DaemonInfo{pid=7941, address=[47100ef7-a38a-4291-b6bb-3abfea089992 port:56262, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]], idle=false, lastBusy=1465373136464, context=DefaultDaemonContext[uid=95ea54a7-c562-4942-aee2-7d257c71c7f1,javaHome=/usr/lib/jvm/java-8-oracle,daemonRegistryDir=/home/jyoti/cache/daemon,pid=7941,idleTimeout=120000,daemonOpts=-Xmx2048M,-Dfile.encoding=UTF-8,-Duser.country=IN,-Duser.language=en,-Duser.variant]} (build should be starting).
The client will now receive all logging from the daemon (pid: 7941). The daemon log file: /home/jyoti/cache/daemon/2.14-rc-2/daemon-7941.out.log
Executing build with daemon context: DefaultDaemonContext[uid=95ea54a7-c562-4942-aee2-7d257c71c7f1,javaHome=/usr/lib/jvm/java-8-oracle,daemonRegistryDir=/home/jyoti/cache/daemon,pid=7941,idleTimeout=120000,daemonOpts=-Xmx2048M,-Dfile.encoding=UTF-8,-Duser.country=IN,-Duser.language=en,-Duser.variant]
Starting Build
Evaluating root project 'buildSrc' using build file '/home/jyoti/repo/dev/droidmate/buildSrc/build.gradle'.
Constructor DefaultSourceDirectorySet(String, FileResolver) has been deprecated and is scheduled to be removed in Gradle 3.0
Selected primary task 'build' from project :
Creating In-memory cache of /home/jyoti/repo/dev/droidmate/buildSrc/.gradle/2.14-rc-2/taskArtifacts/fileHashes.bin: MaxSize{878900}
Creating In-memory cache of /home/jyoti/repo/dev/droidmate/buildSrc/.gradle/2.14-rc-2/taskArtifacts/treeSnapshots.bin: MaxSize{43900}
Creating In-memory cache of /home/jyoti/repo/dev/droidmate/buildSrc/.gradle/2.14-rc-2/taskArtifacts/treeSnapshotUsage.bin: MaxSize{43900}
Creating In-memory cache of /home/jyoti/repo/dev/droidmate/buildSrc/.gradle/2.14-rc-2/taskArtifacts/fileSnapshotsToTreeSnapshotsIndex.bin: MaxSize{21900}
Creating In-memory cache of /home/jyoti/repo/dev/droidmate/buildSrc/.gradle/2.14-rc-2/taskArtifacts/fileSnapshots.bin: MaxSize{21900}
Creating In-memory cache of /home/jyoti/repo/dev/droidmate/buildSrc/.gradle/2.14-rc-2/taskArtifacts/taskArtifacts.bin: MaxSize{4300}
:compileKotlin (Thread[Daemon worker,5,main]) started.
:buildSrc:compileKotlin
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/main/java', not found
Invalidating in-memory cache of /home/jyoti/repo/dev/droidmate/buildSrc/.gradle/2.14-rc-2/taskArtifacts/treeSnapshots.bin
Invalidating in-memory cache of /home/jyoti/repo/dev/droidmate/buildSrc/.gradle/2.14-rc-2/taskArtifacts/treeSnapshotUsage.bin
Invalidating in-memory cache of /home/jyoti/repo/dev/droidmate/buildSrc/.gradle/2.14-rc-2/taskArtifacts/fileSnapshots.bin
Invalidating in-memory cache of /home/jyoti/repo/dev/droidmate/buildSrc/.gradle/2.14-rc-2/taskArtifacts/fileSnapshotsToTreeSnapshotsIndex.bin
Invalidating in-memory cache of /home/jyoti/repo/dev/droidmate/buildSrc/.gradle/2.14-rc-2/taskArtifacts/taskArtifacts.bin
Invalidating in-memory cache of /home/jyoti/repo/dev/droidmate/buildSrc/.gradle/2.14-rc-2/taskArtifacts/fileHashes.bin
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/main/java', not found
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/main/java', not found
Skipping task ':compileKotlin' as it is up-to-date (took 0.068 secs).
:buildSrc:compileKotlin UP-TO-DATE
:compileKotlin (Thread[Daemon worker,5,main]) completed. Took 0.107 secs.
:compileJava (Thread[Daemon worker,5,main]) started.
:buildSrc:compileJava
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/main/java', not found
Skipping task ':compileJava' as it has no source files.
:buildSrc:compileJava UP-TO-DATE
:compileJava (Thread[Daemon worker,5,main]) completed. Took 0.005 secs.
:compileGroovy (Thread[Daemon worker,5,main]) started.
:buildSrc:compileGroovy
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/main/groovy', not found
Skipping task ':compileGroovy' as it has no source files.
:buildSrc:compileGroovy UP-TO-DATE
:compileGroovy (Thread[Daemon worker,5,main]) completed. Took 0.004 secs.
:processResources (Thread[Daemon worker,5,main]) started.
:buildSrc:processResources
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/main/resources', not found
Skipping task ':processResources' as it has no source files.
:buildSrc:processResources UP-TO-DATE
:processResources (Thread[Daemon worker,5,main]) completed. Took 0.008 secs.
:classes (Thread[Daemon worker,5,main]) started.
:buildSrc:classes
Skipping task ':classes' as it has no actions.
:buildSrc:classes UP-TO-DATE
:classes (Thread[Daemon worker,5,main]) completed. Took 0.003 secs.
:jar (Thread[Daemon worker,5,main]) started.
:buildSrc:jar
Skipping task ':jar' as it is up-to-date (took 0.009 secs).
:buildSrc:jar UP-TO-DATE
:jar (Thread[Daemon worker,5,main]) completed. Took 0.014 secs.
:sourcesJar (Thread[Daemon worker,5,main]) started.
:buildSrc:sourcesJar
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/main/resources', not found
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/main/java', not found
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/main/groovy', not found
Skipping task ':sourcesJar' as it is up-to-date (took 0.01 secs).
:buildSrc:sourcesJar UP-TO-DATE
:sourcesJar (Thread[Daemon worker,5,main]) completed. Took 0.014 secs.
:assemble (Thread[Daemon worker,5,main]) started.
:buildSrc:assemble
Skipping task ':assemble' as it has no actions.
:buildSrc:assemble UP-TO-DATE
:assemble (Thread[Daemon worker,5,main]) completed. Took 0.003 secs.
:compileTestKotlin (Thread[Daemon worker,5,main]) started.
:buildSrc:compileTestKotlin
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/test/java', not found
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/test/java', not found
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/test/java', not found
Skipping task ':compileTestKotlin' as it is up-to-date (took 0.054 secs).
:buildSrc:compileTestKotlin UP-TO-DATE
:compileTestKotlin (Thread[Daemon worker,5,main]) completed. Took 0.064 secs.
:compileTestJava (Thread[Daemon worker,5,main]) started.
:buildSrc:compileTestJava
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/test/java', not found
Skipping task ':compileTestJava' as it has no source files.
:buildSrc:compileTestJava UP-TO-DATE
:compileTestJava (Thread[Daemon worker,5,main]) completed. Took 0.002 secs.
:compileTestGroovy (Thread[Daemon worker,5,main]) started.
:buildSrc:compileTestGroovy
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/test/groovy', not found
Skipping task ':compileTestGroovy' as it has no source files.
:buildSrc:compileTestGroovy UP-TO-DATE
:compileTestGroovy (Thread[Daemon worker,5,main]) completed. Took 0.003 secs.
:processTestResources (Thread[Daemon worker,5,main]) started.
:buildSrc:processTestResources
file or directory '/home/jyoti/repo/dev/droidmate/buildSrc/src/test/resources', not found
Skipping task ':processTestResources' as it has no source files.
:buildSrc:processTestResources UP-TO-DATE
:processTestResources (Thread[Daemon worker,5,main]) completed. Took 0.001 secs.
:testClasses (Thread[Daemon worker,5,main]) started.
:buildSrc:testClasses
Skipping task ':testClasses' as it has no actions.
:buildSrc:testClasses UP-TO-DATE
:testClasses (Thread[Daemon worker,5,main]) completed. Took 0.001 secs.
:test (Thread[Daemon worker,5,main]) started.
:buildSrc:test
Skipping task ':test' as it is up-to-date (took 0.029 secs).
:buildSrc:test UP-TO-DATE
:test (Thread[Daemon worker,5,main]) completed. Took 0.048 secs.
:check (Thread[Daemon worker,5,main]) started.
:buildSrc:check
Skipping task ':check' as it has no actions.
:buildSrc:check UP-TO-DATE
:check (Thread[Daemon worker,5,main]) completed. Took 0.001 secs.
:build (Thread[Daemon worker,5,main]) started.
:buildSrc:build
Skipping task ':build' as it has no actions.
:buildSrc:build UP-TO-DATE
:build (Thread[Daemon worker,5,main]) completed. Took 0.004 secs.
Stopped 0 compiler daemon(s).
Settings evaluated using settings file '/home/jyoti/repo/dev/droidmate/settings.gradle'.
Projects loaded. Root project using build file '/home/jyoti/repo/dev/droidmate/build.gradle'.
Included projects: [root project 'droidmate', project ':DummyAndroidApp', project ':projects', project ':projects:apk-inliner', project ':projects:command', project ':projects:core', project ':projects:lib-common', project ':projects:lib-kotlin', project ':projects:monitor-generator', project ':projects:monitor-template', project ':projects:reporter', project ':projects:uiautomator-daemon', project ':projects:uiautomator-daemon-lib', project ':projects:uiautomator2-daemon-proxy']
Evaluating root project 'droidmate' using build file '/home/jyoti/repo/dev/droidmate/build.gradle'.
Evaluating project ':DummyAndroidApp' using build file '/home/jyoti/repo/dev/droidmate/DummyAndroidApp/build.gradle'.
Evaluating project ':projects' using build file '/home/jyoti/repo/dev/droidmate/projects/build.gradle'.
Evaluating project ':projects:apk-inliner' using build file '/home/jyoti/repo/dev/droidmate/projects/apk-inliner/build.gradle'.
Evaluating project ':projects:command' using build file '/home/jyoti/repo/dev/droidmate/projects/command/build.gradle'.
Evaluating project ':projects:core' using build file '/home/jyoti/repo/dev/droidmate/projects/core/build.gradle'.
Evaluating project ':projects:uiautomator-daemon' using build file '/home/jyoti/repo/dev/droidmate/projects/uiautomator-daemon/build.gradle'.
Evaluating project ':projects:uiautomator-daemon-lib' using build file '/home/jyoti/repo/dev/droidmate/projects/uiautomator-daemon-lib/build.gradle'.
Evaluating project ':projects:reporter' using build file '/home/jyoti/repo/dev/droidmate/projects/reporter/build.gradle'.
Evaluating project ':projects:lib-kotlin' using build file '/home/jyoti/repo/dev/droidmate/projects/lib-kotlin/build.gradle'.
Evaluating project ':projects:lib-common' using build file '/home/jyoti/repo/dev/droidmate/projects/lib-common/build.gradle'.
Evaluating project ':projects:monitor-generator' using build file '/home/jyoti/repo/dev/droidmate/projects/monitor-generator/build.gradle'.
Evaluating project ':projects:monitor-template' using build file '/home/jyoti/repo/dev/droidmate/projects/monitor-template/build.gradle'.
Evaluating project ':projects:uiautomator2-daemon-proxy' using build file '/home/jyoti/repo/dev/droidmate/projects/uiautomator2-daemon-proxy/build.gradle'.
All projects evaluated.

FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :projects:command:run from command line.
> Unknown command-line option '-n'.

* Try:
Run gradlew help --task :projects:command:run to get task usage details. Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED
-------------------------------------------------------------------

Please tell what can be the reason of this build fail?

Regards
Jyoti

**Comment by konrad-jamrozik** [comment]
Please read ["running droidmate from sources" in RUNNING.md](RUNNING.md#running-droidmate-from-sources). It states you have to provide command line parameters in the `args.txt` file.

If you wish to customize how DroidMate reads args, edit [this function](https://github.com/konrad-jamrozik/droidmate/blob/d6a5f94af10981a9ee982bdb7d23072a482c990a/dev/droidmate/projects/command/build.gradle#L54-L65).

**Comment by jyotigajrani** [comment]
Thanks konrad.
I am able to inline the apks now. It generate inlined apk in the apks/inlined folder.

But when I run it for that apk, Build is successful without any error message but there is no exploration of app in emulator. What can be the reason of that?
I am using the same command:
./gradlew :projects:command:run

Thanks.
Jyoti

**Comment by konrad-jamrozik** [comment]
Closing this issue as the problem described was solved. See my email regarding your current problem.

**Comment by jyotigajrani** [comment]
Dear Konrad,

Sorry to disturb you again after long break.
I am attaching the whole log folder.
Still I am not able to see the app running in emulator.
It says :No apks found! Apks were expected to be found in:
/media/jyoti/a56a27d9-6252-44a9-a4c1-1862971af1d4/jyoti/PHD/droidmate-master/dev/droidmate/apks/inlined

Although I can see apk building in inlined folder.
I will be thankful to you.

Regards


On Fri, Jun 10, 2016 at 1:49 AM, Konrad Jamrozik <notifications@github.com>
wrote:

> Closed #4 <https://github.com/konrad-jamrozik/droidmate/issues/4>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/konrad-jamrozik/droidmate/issues/4#event-687767320>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMUHzZKDCnBemZ_ttBX1wiJFux28uiPaks5qKHU5gaJpZM4IwtbD>
> .
>



-- 


*RegardsJyoti Gajrani*
*Assistant Professor **(Computer Engineering) *
*Govt. Engg. College, Ajmer (Rajasthan)*

**Comment by konrad-jamrozik** [comment]
Jyoti,

 

I am sorry, but I do not see any log folder attached.

**Comment by jyotigajrani** [comment]
Hi Konard,

PFA logs

Regards

[logs.tar.gz](https://github.com/konrad-jamrozik/droidmate/files/785734/logs.tar.gz)

**Comment by konrad-jamrozik** [comment]
Jyoti, in the run_data.txt log there is a line:
args={-apksDir=apks/inlined,,-resetEvery=15,-timeLimit=120,-softReset=true,-randomSeed=0,-inline}
The last argument denotes you want to inline the apks, not do a proper DroidMate run (see doc).

Then in the master_log.txt you have:
2017-02-16 21:03:30.001 WARN  org.droidmate.command.InlineCommand      No non-inlined apks found. Aborting.

Remove the -inline flag and ensure that all apks have been inlined. DroidMate appends "-inline" to apk name after inlining, and uses it to recognize inlined apks, so if you didn't tamper with its name, it will just work. If you try to make DroidMate run on non-inlined apks, you will not see any API call logs in resulting serialized output or logs.
